version: "3.9"
services:
    
    
    medicalmgr:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: Pw@mm2021
            ACCEPT_EULA: Y
        ports:
            - "1433:1433"
        container_name: mmm_mmsql_2019
    
    web:
        image:  medical-manager:latest 
        ports:
            - "8000:80"
        container_name: web_application
        depends_on:
            - medicalmgr
        environment:
            WAIT_HOSTS: medicalmgr:1433
            WAIT_HOSTS_TIMEOUT: 90
            WAIT_SLEEP_INTERVAL: 15
            WAIT_HOST_CONNECT_TIMEOUT: 30

