version: "3.9"
services:
    web:
        image: medicalmanager_web:latest
        ports:
            - "8000:80"
        container_name: web_application
        depends_on:
            - medicalmgr
    
    medicalmgr:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: Pw@mm2021
            ACCEPT_EULA: Y
        ports:
            - "1433:1433"
        container_name: mmm_mmsql_2019





